DROP DATABASE IF EXISTS visittypeservice;
DROP USER IF EXISTS `visit_type_service`@`%`;
CREATE DATABASE IF NOT EXISTS visittypeservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `visit_type_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `visittypeservice`.* TO `visit_type_service`@`%`;
FLUSH PRIVILEGES;

